// Table de correspondance Code SAP <-> Code QDV, extraite de l'onglet
// "Correspondance" du classeur modèle GOAT fourni par Julien (voir aussi le
// doc "correspondance-sap-qdv.md" du projet INEO sur claude.ai, qui porte la
// même donnée). codeQdv est un nombre (ou null quand ce code SAP n'a pas de
// correspondance côté types de FO Électricité).
export const CORRESPONDANCE_SAP_QDV = [
  { codeSap: "ACIE", libelleSap: "ACIER", codeQdv: null, libelleQdv: null },
  { codeSap: "AINT", libelleSap: "ANTI-INTRUSION", codeQdv: 1, libelleQdv: "Anti-intrusion" },
  { codeSap: "APMA", libelleSap: "APPEL MALADE", codeQdv: 3, libelleQdv: "Appel Malade" },
  { codeSap: "APPA", libelleSap: "APPAREILLAGE", codeQdv: 2, libelleQdv: "Appareillage" },
  { codeSap: "AUDV", libelleSap: "MATRICAGE AUDIOVISUEL", codeQdv: null, libelleQdv: null },
  { codeSap: "AUTO", libelleSap: "AUTOMATISME & CONTRÔLE", codeQdv: 4, libelleQdv: "Automatisme & Contrôle" },
  { codeSap: "CACC", libelleSap: "CONTRÔLE D'ACCÈS", codeQdv: 11, libelleQdv: "Contrôle d'accès" },
  { codeSap: "CANA", libelleSap: "CANALISATION", codeQdv: 21, libelleQdv: "Gaines préfabriquées" },
  { codeSap: "CHCB", libelleSap: "CHEMIN DE CÂBLES", codeQdv: 8, libelleQdv: "Chemin de câbles" },
  { codeSap: "CLIM", libelleSap: "CHAUFFAGE / CLIM / VENTILATION", codeQdv: 7, libelleQdv: "Chauffage / Clim / Ventilation" },
  { codeSap: "COFL", libelleSap: "COURANTS FAIBLES DIVERS", codeQdv: 12, libelleQdv: "Courants faibles divers" },
  { codeSap: "COMP", libelleSap: "COMPENSATION FILTRAGE", codeQdv: 10, libelleQdv: "Compensation Filtrage" },
  { codeSap: "COND", libelleSap: "CÂBLES RÉSEAUX", codeQdv: 41, libelleQdv: "Informatique / Réseau" },
  { codeSap: "DECH", libelleSap: "TRAITEMENT DÉCHETS", codeQdv: 38, libelleQdv: "Traitement déchets" },
  { codeSap: "DHEU", libelleSap: "DISTRIBUTION DE L'HEURE", codeQdv: 13, libelleQdv: "Distribution de l'heure" },
  { codeSap: "DISP", libelleSap: "DISPLAY / MONITEURS PRO", codeQdv: null, libelleQdv: null },
  { codeSap: "DIVE", libelleSap: "DIVERS : ACCESSOIRES ET CONSOMMABLES", codeQdv: 14, libelleQdv: "Divers : accessoires et consommables" },
  { codeSap: "ECLE", libelleSap: "ECLAIRAGE EXTÉRIEUR", codeQdv: 17, libelleQdv: "Eclairage extérieur" },
  { codeSap: "ECLN", libelleSap: "ECLAIRAGE", codeQdv: 15, libelleQdv: "Eclairage" },
  { codeSap: "ECLS", libelleSap: "ECLAIRAGE DE SÉCURITÉ", codeQdv: 16, libelleQdv: "Eclairage de sécurité" },
  { codeSap: "ELEC", libelleSap: "ELECTRICITE", codeQdv: null, libelleQdv: null },
  { codeSap: "EQPR", libelleSap: "INFORMATIQUE / RÉSEAU", codeQdv: 5, libelleQdv: "Câbles réseaux" },
  { codeSap: "FILC", libelleSap: "FILS ET CÂBLES CFO/CFA", codeQdv: 18, libelleQdv: "Fils et Câbles CFO/CFA" },
  { codeSap: "FOUD", libelleSap: "FOUDRE / TERRE / LEQ", codeQdv: 19, libelleQdv: "Foudre / Terre / LEQ" },
  { codeSap: "GOUL", libelleSap: "GOULOTTES", codeQdv: 22, libelleQdv: "Goulottes" },
  { codeSap: "GREL", libelleSap: "GROUPES ÉLECTROGÈNES", codeQdv: 23, libelleQdv: "Groupes électrogènes" },
  { codeSap: "GTCA", libelleSap: "GTC ET ALARMES TECHNIQUES", codeQdv: 24, libelleQdv: "GTC et Alarmes Techniques" },
  { codeSap: "INCE", libelleSap: "INSTALLATIONS INCENDIE", codeQdv: 25, libelleQdv: "Installations INCENDIE" },
  { codeSap: "INST", libelleSap: "INSTRUMENTATION", codeQdv: 26, libelleQdv: "Instrumentation" },
  { codeSap: "INST-CH", libelleSap: "INSTALLATION CHANTIER", codeQdv: null, libelleQdv: null },
  { codeSap: "IPHO", libelleSap: "INTERPHONIE", codeQdv: 27, libelleQdv: "Interphonie" },
  { codeSap: "LANT", libelleSap: "LANTERNES ET CANDÉLABRES", codeQdv: 28, libelleQdv: "Lanternes et candélabres" },
  { codeSap: "LOCA", libelleSap: "LOCATION", codeQdv: 29, libelleQdv: "Location" },
  { codeSap: "LOKI", libelleSap: "LOKI", codeQdv: null, libelleQdv: null },
  { codeSap: "MATE", libelleSap: "MATÉRIAUX / AGRÉGATS", codeQdv: null, libelleQdv: null },
  { codeSap: "MCAT", libelleSap: "MATÉRIEL CATÉNAIRE", codeQdv: null, libelleQdv: null },
  { codeSap: "MSIG", libelleSap: "MATÉRIEL SIGNALISATION", codeQdv: null, libelleQdv: null },
  { codeSap: "ONDU", libelleSap: "ONDULEURS", codeQdv: 31, libelleQdv: "Onduleurs" },
  { codeSap: "PHOT", libelleSap: "PHOTOVOLTAÏQUE", codeQdv: 32, libelleQdv: "Photovoltaïque" },
  { codeSap: "POST", libelleSap: "POSTES ET TRANSFOS", codeQdv: 33, libelleQdv: "Postes et Transfos" },
  { codeSap: "POTX", libelleSap: "MATS, PYLONES", codeQdv: null, libelleQdv: null },
  { codeSap: "PREF", libelleSap: "GAINES PRÉFABRIQUÉES", codeQdv: null, libelleQdv: null },
  { codeSap: "PROGTEST", libelleSap: "TEST PROG", codeQdv: null, libelleQdv: null },
  { codeSap: "SONO", libelleSap: "SONORISATION", codeQdv: 35, libelleQdv: "Sonorisation" },
  { codeSap: "SURV", libelleSap: "VIDEO-SURVEILLANCE", codeQdv: 42, libelleQdv: "Video-Surveillance" },
  { codeSap: "TABL", libelleSap: "TABLEAUX ÉLECTRIQUES / APPAREILLAGE BT", codeQdv: 36, libelleQdv: "Tableaux électriques / Appareillage BT" },
  { codeSap: "TELE", libelleSap: "TV", codeQdv: 40, libelleQdv: "TV" },
  { codeSap: "TPHO", libelleSap: "EQUIPEMENTS TRANSMISSION / TÉLÉCOM", codeQdv: 37, libelleQdv: "Téléphonie" },
  { codeSap: "TUBE", libelleSap: "TUBES / BD / PIEUVRES", codeQdv: 39, libelleQdv: "Tubes / BD / Pieuvres" },
];
