// Listes des types de FO (Fournitures) et de MO (Main d'œuvre), issues du
// référentiel de codification des devis Électricité (colonnes "TYPE DE FO" /
// "TYPE DE MO" du classeur fourni par Julien). Utilisées pour proposer un
// menu déroulant lors de la modification du type de FO/MO d'une ligne.
export const LISTE_TYPES_FO = [
  { code: "1", label: "Anti-intrusion" },
  { code: "2", label: "Appareillage" },
  { code: "3", label: "Appel Malade" },
  { code: "4", label: "Automatisme & Contrôle" },
  { code: "5", label: "Câbles réseaux" },
  { code: "7", label: "Chauffage / Clim / Ventilation" },
  { code: "8", label: "Chemin de câbles" },
  { code: "10", label: "Compensation Filtrage" },
  { code: "11", label: "Contrôle d'accès" },
  { code: "12", label: "Courants faibles divers" },
  { code: "13", label: "Distribution de l'heure" },
  { code: "14", label: "Divers : accessoires et consommables" },
  { code: "15", label: "Eclairage" },
  { code: "151", label: "Eclairage bureau" },
  { code: "152", label: "Eclairage industriel" },
  { code: "153", label: "Eclairage sdV" },
  { code: "16", label: "Eclairage de sécurité" },
  { code: "17", label: "Eclairage extérieur" },
  { code: "18", label: "Fils et Câbles CFO/CFA" },
  { code: "19", label: "Foudre / Terre / LEQ" },
  { code: "21", label: "Gaines préfabriquées" },
  { code: "22", label: "Goulottes" },
  { code: "23", label: "Groupes électrogènes" },
  { code: "24", label: "GTC et Alarmes Techniques" },
  { code: "25", label: "Installations INCENDIE" },
  { code: "26", label: "Instrumentation" },
  { code: "27", label: "Interphonie" },
  { code: "28", label: "Lanternes et candélabres" },
  { code: "29", label: "Location" },
  { code: "31", label: "Onduleurs" },
  { code: "32", label: "Photovoltaïque" },
  { code: "321", label: "Modules" },
  { code: "322", label: "Système d'intégration" },
  { code: "323", label: "Photovoltaïque 3" },
  { code: "324", label: "Photovoltaïque 4" },
  { code: "33", label: "Postes et Transfos" },
  { code: "35", label: "Sonorisation" },
  { code: "36", label: "Tableaux électriques / Appareillage BT" },
  { code: "37", label: "Téléphonie" },
  { code: "38", label: "Traitement déchets" },
  { code: "39", label: "Tubes / BD / Pieuvres" },
  { code: "40", label: "TV" },
  { code: "41", label: "Informatique / Réseau" },
  { code: "42", label: "Video-Surveillance" },
  { code: "STOR", label: "Sous Traitance Ordinaire" },
  { code: "70", label: "ST Eclairage" },
  { code: "71", label: "ST VDI" },
  { code: "72", label: "ST Câbles CFO" },
  { code: "73", label: "ST Câbles CFA" },
  { code: "74", label: "ST Câbles CFO-CFA" },
  { code: "75", label: "STO5" },
  { code: "76", label: "STO6" },
  { code: "77", label: "STO7" },
  { code: "78", label: "STO8" },
  { code: "79", label: "STO9" },
  { code: "STIN", label: "Sous Traitance Ineo" },
  { code: "80", label: "STI1" },
  { code: "81", label: "STI2" },
  { code: "82", label: "STI3" },
  { code: "83", label: "STI4" },
  { code: "84", label: "STI5" },
  { code: "85", label: "STI6" },
  { code: "STPD", label: "Sous Traitance Paiement Direct" },
  { code: "90", label: "STPD1" },
  { code: "91", label: "STPD2" },
  { code: "92", label: "STPD3" },
  { code: "93", label: "STPD4" },
  { code: "94", label: "STPD5" },
  { code: "95", label: "STPD6" },
  { code: "COT", label: "Co-Traitance" },
  { code: "COT1", label: "Co-Traitant 1" },
  { code: "COT2", label: "Co-Traitant 2" },
  { code: "COT3", label: "Co-Traitant 3" },
  { code: "COT4", label: "Co-Traitant 4" },
  { code: "COT5", label: "Co-Traitant 5" },
  { code: "DV", label: "FRAIS DIVERS" },
  { code: "CHIF", label: "Etudes Chiffrage" },
  { code: "LOC", label: "Location Materiel Outillage" },
  { code: "TAX", label: "Impots, Taxes, PUC/TUC/TRC" },
  { code: "DIV", label: "Frais divers, Provision autre frais" },
  { code: "ALEA", label: "Aléas" },
  { code: "DEP", label: "Frais Deplacement" },
  { code: "MINT", label: "Materiel Interne" },
];

export const LISTE_TYPES_MO = [
  { code: "PR", label: "PRODUCTION" },
  { code: "1", label: "TECHN. MAINTENANCE" },
  { code: "2", label: "CONDUCTEUR TRAVAUX" },
  { code: "3", label: "CHEF DE CHANTIER" },
  { code: "5", label: "CHEF EQUIPE" },
  { code: "6", label: "MONTEUR QUALIFIE" },
  { code: "EA", label: "ENCADREMENT AFFAIRES" },
  { code: "51", label: "ASSISTANT RA" },
  { code: "52", label: "CADRE SENIOR (RAP)" },
  { code: "53", label: "CADRE" },
  { code: "54", label: "CADRE JUNIOR" },
  { code: "ET", label: "ETUDES" },
  { code: "61", label: "PROJETEUR BE" },
  { code: "63", label: "AUTOMATICIEN" },
  { code: "64", label: "TECHNICIEN" },
  { code: "65", label: "ETUDES IAC" },
  { code: "EX", label: "EXTERNES" },
  { code: "E1", label: "ETUDES EXTERNES" },
  { code: "E2", label: "ENCADREMENT EXTERNE" },
  { code: "E3", label: "PRODUCTION EXTERNE" },
];

// Format utilisé dans les devis importés (voir formatTypeFo dans
// ElectriciteSiteDetail.jsx) : "<code>  [<libellé>]", par ex.
// "4  [Automatisme & Contrôle]".
export function valeurType(code, label) {
  return code + "  [" + label + "]";
}
